# Generated by Django 4.1.8 on 2023-04-27 18:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_recipe_cook_time_recipe_preparation_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("favorites", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "recipe")},
        ),
    ]
