# Generated by Django 4.1.8 on 2023-04-28 15:47

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="recipes")),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("vegan", "Vegan"),
                                ("vegetarian", "Vegetarian"),
                                ("gluten-free", "Gluten Free"),
                                ("dairy-free", "Dairy Free"),
                                ("Indian", "Indian"),
                                ("Italian", "Italian"),
                                ("Mexican", "Mexican"),
                                ("Chinese", "Chinese"),
                                ("Japanese", "Japanese"),
                                ("Thai", "Thai"),
                                ("Korean", "Korean"),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "meal_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("breakfast", "Breakfast"),
                                ("lunch", "Lunch"),
                                ("dinner", "Dinner"),
                                ("snack", "Snack"),
                                ("dessert", "Dessert"),
                                ("beverage", "Beverage"),
                                ("other", "Other"),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ingredients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "instructions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        size=None,
                    ),
                ),
                ("servings", models.PositiveIntegerField()),
                ("prep_time_in_minutes", models.PositiveIntegerField()),
                ("cook_time_in_minutes", models.PositiveIntegerField()),
                ("total_time", models.PositiveIntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
