# Generated by Django 4.1.8 on 2023-04-26 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                ],
                default=django.utils.timezone.now,
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
