# Generated by Django 4.1.8 on 2023-04-27 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_recipe_options_recipe_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("snack", "Snack"),
                    ("dessert", "Dessert"),
                    ("beverage", "Beverage"),
                    ("other", "Other"),
                ],
                default=django.utils.timezone.now,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.CharField(
                choices=[
                    ("vegan", "Vegan"),
                    ("vegetarian", "Vegetarian"),
                    ("gluten-free", "Gluten Free"),
                    ("dairy-free", "Dairy Free"),
                    ("Indian", "Indian"),
                    ("Italian", "Italian"),
                    ("Mexican", "Mexican"),
                    ("Chinese", "Chinese"),
                    ("Japanese", "Japanese"),
                    ("Thai", "Thai"),
                    ("Korean", "Korean"),
                ],
                max_length=255,
            ),
        ),
    ]
