# Generated by Django 4.1.8 on 2023-04-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_recipe_meal_type_alter_recipe_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
