# Generated by Django 4.1.8 on 2023-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_recipe_servings"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cook_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recipe",
            name="preparation_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recipe",
            name="total_time",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
